name: Run PHPCS, PHPLint and Cypress

on: [pull_request]

jobs:
    # PHPCS:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2

    #         - name: Install Composer dependencies
    #           uses: ramsey/composer-install@v1

    #         - name: Show PHPCS sniffs
    #           run: ./vendor/bin/phpcs -i

    #         - name: Show PHPCS version
    #           run: ./vendor/bin/phpcs --version

    #         - name: Run PHP_CodeSniffer
    #           run: composer phpcs

    # PHPLint:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2

    #         - name: Install Composer dependencies
    #           uses: ramsey/composer-install@v1

    #         - name: Show PHPLint version info
    #           run: ./vendor/bin/phplint --version

    #         - name: Run PHPLint
    #           run: composer phplint

    Cypress:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm install

            - name: Start testing environment
              run: npm run wp-env start

            - name: Configure testing environment
              run: |
                  npm run wp-env run tests-cli wp theme install astra
                  npm run wp-env run tests-cli wp theme install atomic-blocks
            # - name: Configure testing environment
            #   run: |
            #       chmod +x cypress/bin/setup.sh
            #       cypress/bin/setup.sh
            #   shell: bash
            # - name: Cypress run
            #   uses: cypress-io/github-action@v2
            #   with:
            #       wait-on: 'http://localhost:8889'
            #       browser: chrome
            #       headless: true
