name: Run PHPCS, PHPLint, Psalm and Cypress

on: [pull_request, push]

jobs:
  PHPCS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Show PHPCS sniffs
        run: ./vendor/bin/phpcs -i

      - name: Show PHPCS version
        run: ./vendor/bin/phpcs --version

      - name: Run PHP_CodeSniffer
        run: composer phpcs

  PHPLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Show PHPLint version info
        run: ./vendor/bin/phplint --version

      - name: Run PHPLint
        run: composer phplint

  Psalm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Show PHPCS sniffs
        run: ./vendor/bin/phpcs -i

      - name: Show version info
        run: ./vendor/bin/psalm --version

      - name: Run Psalm
        run: composer psalm

  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start local server
        run: npm run wp-env start

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8888

      - name: Run Cypress tests
        run: npx cypress run --config-file=cypress.config.js --browser chrome --headless
